- name: "NOTSCORED | 4.1.1.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file"
      line: "max_log_file = {{ rhel7cis_max_log_file }}"
      state: present
      backup: yes
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.1
      - notscored

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: '{{ item.rxp }}'
      line: '{{ item.line }}'
      state: present
      create: yes
  with_items:

      - { rxp: '^space_left_action', line: 'space_left_action = {{ rhel7cis_space_left_action }}' }
      - { rxp: '^action_mail_acct', line: 'action_mail_acct = {{ rhel7cis_action_mail_acct }}' }
      - { rxp: '^admin_space_left_action', line: 'admin_space_left_action = {{ rhel7cis_admin_space_left_action }}' }
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.2
      - scored

- name: "SCORED | 4.1.1.3 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ rhel7cis_max_log_file_action }}"
      state: present
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.1.3
      - scored

- name: "SCORED | 4.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
    - rhel7cis_enable_auditd is defined and rhel7cis_enable_auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.2
      - scored

- name: "SCORED | 4.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="'
      line: 'GRUB_CMDLINE_LINUX="audit=1"'
      state: present
      create: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.3
      - scored

- name: "SCORED | 4.1.4 | PATCH | Ensure events that modify date and time information are collected"
  template:
       src: audit/rhel7cis_rule_4_1_4.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_4.rules
       backup: yes
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.4
      - scored

- name: "SCORED | 4.1.5 | PATCH | Ensure events that modify user/group information are collected"
  template:
       src: audit/rhel7cis_rule_4_1_5.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_5.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.5
      - scored

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify the system's network environment are collected"
  template:
       src: audit/rhel7cis_rule_4_1_6.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_6.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.6
      - scored

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  template:
       src: audit/rhel7cis_rule_4_1_7.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_7.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.7
      - scored

- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  template:
       src: audit/rhel7cis_rule_4_1_8.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_8.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.8
      - scored

- name: "SCORED | 4.1.9 | PATCH | Ensure session initiation information is collected"
  template:
       src: audit/rhel7cis_rule_4_1_9.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_9.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.9
      - scored

- name: "SCORED | 4.1.10 | PATCH | Ensure discretionary access control permission modification events are collected"
  template:
       src: audit/rhel7cis_rule_4_1_10.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_10.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.10
      - scored

- name: "SCORED | 4.1.11 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  template:
       src: audit/rhel7cis_rule_4_1_11.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_11.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.11
      - scored

- name: "SCORED | 4.1.12 | CHECK | Ensure use of privileged commands is collected"
  shell: >-
    set -o pipefail &&
      for i in $(df | grep '^/dev' | awk '{ print $NF }'); do
        find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null;
    done
  register: priv_procs
  changed_when: no
  check_mode: no
  when:
      - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
      - level2
      - check
      - rule_4.1.12
      - scored

- name: "SCORED | 4.1.12 | PATCH | Ensure use of privileged commands is collected"
  template:
       src: audit/rhel7cis_rule_4_1_12.rules.j2
       dest: /etc/audit/rules.d/rhel7cis_rule_4_1_12.rules
       owner: root
       group: root
       mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.12
      - scored

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  template:
      src: audit/rhel7cis_rule_4_1_13.rules.j2
      dest: /etc/audit/rules.d/rhel7cis_rule_4_1_13.rules
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.13
      - scored

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  template:
      src: audit/rhel7cis_rule_4_1_14.rules.j2
      dest: /etc/audit/rules.d/rhel7cis_rule_4_1_14.rules
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.14
      - scored

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  template:
      src: audit/rhel7cis_rule_4_1_15.rules.j2
      dest: /etc/audit/rules.d/rhel7cis_rule_4_1_15.rules
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.15
      - scored

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  template:
      src: audit/rhel7cis_rule_4_1_16.rules.j2
      dest: /etc/audit/rules.d/rhel7cis_rule_4_1_16.rules
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.16
      - scored

- name: "SCORED | 4.1.17 | PATCH | Ensure kernel module loading and unloading is collected"
  template:
      src: audit/rhel7cis_rule_4_1_17.rules.j2
      dest: /etc/audit/rules.d/rhel7cis_rule_4_1_17.rules
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.17
      - scored

- name: "SCORED | 4.1.18 | PATCH | Ensure the audit configuration is immutable"
  lineinfile:
      dest: /etc/audit/rules.d/audit.rules
      line: '-e 2'
      insertafter: EOF
      state: present
      create: yes
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  notify: restart auditd
  tags:
      - level2
      - auditd
      - patch
      - rule_4.1.18
      - scored

- name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
  yum:
    name: rsyslog
    state: present
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_rsyslog
  tags:
      - level1
      - low
      - patch
      - rule_4.2.3
      - scored

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled"
  service:
    name: rsyslog
    state: started
    enabled: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_rsyslog
  tags:
      - level2
      - patch
      - rule_4.2.1.1
      - scored

- name: "NOTSCORED | 4.2.1.2 | PATCH | Ensure logging is configured"
  template:
      src: rsyslog.conf.j2
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
  notify: "restart rsyslog"
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_log_server is defined
    - rhel7cis_rsyslog
    - rhel7cis_log_server
  tags:
      - level1
      - patch
      - rule_4.2.1.2
      - notscored

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
      create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_rsyslog
  tags:
      - level1
      - patch
      - rule_4.2.1.3
      - scored

- name: "SCORED | 4.2.1.4 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: "^\\*\\.\\*"
    line: "*.* @@{{ rhel7cis_rsyslog_loghost_address }}"
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_rsyslog
  notify: "restart rsyslog"
  tags:
      - level1
      - patch
      - rule_4.2.1.4
      - scored


- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$ModLoad imtcp'
      line: '$ModLoad imtcp'
      create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_log_server is defined
    - rhel7cis_rsyslog
    - rhel7cis_log_server
  notify: "restart rsyslog"
  tags:
      - level1
      - patch
      - rule_4.2.1.5
      - notscored

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$InputTCPServerRun 514'
      line: '$InputTCPServerRun 514'
      create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_rsyslog is defined and rhel7cis_log_server is defined
    - rhel7cis_rsyslog
    - rhel7cis_log_server
  notify: "restart rsyslog"
  tags:
      - level1
      - patch
      - rule_4.2.1.5
      - notscored

- name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
  yum:
    name: syslog-ng
    state: present
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_syslog_ng
  tags:
      - level1
      - level2
      - low
      - patch
      - rule_4.2.3
      - scored

- name: "SCORED | 4.2.2.1 | PATCH | Ensure syslog-ng service is enabled"
  block:
     - name: Disable the rsyslog service
       service: 
         name: rsyslog
         state: stopped
         enabled: no

     - name: Enable the syslog-ng service
       service:
         name: syslog-ng
         state: started
         enabled: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_syslog_ng
  tags:
      - level1
      - patch
      - rule_4.2.2.1
      - scored

- name: "NOTSCORED | 4.2.2.2 | PATCH | Ensure logging is configured"
  template:
      src: syslog-ng.conf.j2
      dest: /etc/syslog-ng/syslog-ng.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_log_server is defined
    - rhel7cis_syslog_ng
    - rhel7cis_log_server
  notify: restart syslog-ng
  tags:
      - level1
      - patch
      - rule_4.2.2.2
      - notscored

- name: "SCORED | 4.2.2.3 | PATCH | Ensure syslog-ng default file permissions configured"
  lineinfile:
    dest: '/etc/syslog-ng/syslog-ng.conf'
    line: 'options { chain_hostnames(off); flush_lines(0); perm(0640); stats_freq(3600); threaded(yes); };'
    state: present
    create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_log_server is defined
    - rhel7cis_syslog_ng
    - rhel7cis_log_server
  tags:
      - level1
      - patch
      - rule_4.2.2.3
      - scored

- name: "NOTSCORED | 4.2.2.4 | PATCH | Ensure syslog-ng is configured to send logs to a remote log host"
  lineinfile:
      dest: '/etc/syslog-ng/syslog-ng.conf'
      regexp: '^destination logserver'
      line: 'destination logserver { tcp( {{ rhel7cis_syslog_ng_loghost_address }} port(514)); }; log { source(src); destination(logserver); };'
      create: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_log_server is defined
    - rhel7cis_syslog_ng
    - rhel7cis_log_server
  notify: restart syslog-ng
  tags:
      - level1
      - patch
      - rule_4.2.2.4
      - notscored

- name: "NOTSCORED | 4.2.2.5 | PATCH | Ensure remote syslog-ng messages are only accepted on designated log hosts"
  lineinfile:
      dest: '/etc/syslog-ng/syslog-ng.conf'
      line: "{{ item }}"
      insertafter: EOF
      create: yes
  with_items:
      - 'source net{ tcp(); };'
      - 'destination remote { file("/var/log/remote/${FULLHOST}-log"); };'
      - 'log { source(net); destination(remote); };'    
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_syslog_ng is defined and rhel7cis_log_server is defined
    - rhel7cis_syslog_ng
    - rhel7cis_log_server
  notify: restart syslog-ng
  tags:
      - level1
      - patch
      - rule_4.2.2.5
      - notscored

- name: "SCORED | 4.2.4 | CHECK | Ensure permissions on all logfiles are configured"
  shell: "find /var/log -type f"
  register: find_logfiles
  changed_when: false
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
      - level1
      - check
      - rule_4.2.4
      - scored

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
  file:
    path: "{{ item }}"
    mode: 0740
  with_items:
    - "{{ find_logfiles.stdout_lines }}"
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
      - level1
      - patch
      - rule_4.2.4
      - scored

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  lineinfile:
      dest: /etc/logrotate.conf
      regexp: "^#daily"
      line: "daily"
      create: yes
      backup: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
      - level1
      - patch
      - rule_4.3
      - scored
